using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ContosoUniversityMVC.Models
{
    public class Course
    {
        [DatabaseGenerated(DatabaseGeneratedOption.None)] //specifies that primary key values are provided by the user rather than generated by the DB
        [Display(Name = "Number")]
        public int CourseID { get; set; }

        [StringLength(50, MinimumLength = 3)]
        public string Title { get; set; }

        [Range(0, 12)]
        public int Credits { get; set; }

        public int DepartmentID { get; set; }
        //A course is assigned to one department, so there's a DepartmentID foreign key and a Department navigation property for the reasons mentioned above.
        public Department Department { get; set; }
        public ICollection<Enrollment> Enrollments { get; set; } //A course can have any number of students enrolled in it, so the Enrollments navigation property is a collection:
        public ICollection<CourseAssignment> CourseAssignments { get; set; }
        //A course may be taught by multiple instructors, so the CourseAssignments navigation property is a collection
    }
}